version: "3"

services:
  backend:
    build: ./Backend
    container_name: biomechanics-backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend/uploads:/app/uploads
      - ./Frontend:/app/Frontend
    restart: always

