version: '3'

services:
  backend:
    build: ./Backend
    container_name: biomechanics-backend
    ports:
      - "5001:5000"
    volumes:
      - ./Backend/uploads:/app/uploads
      - ./Frontend:/app/Frontend
    restart: always

  slicer:
      build:
        context: .
        dockerfile: Dockerfile.trame-slicer
      platform: linux/amd64
      container_name: trame-slicer
      ports:
        - "8888:8888"
      restart: always
  # slicer:
  #     build:
  #       context: .
  #       dockerfile: Dockerfile.trame-slicer
  #     container_name: trame-slicer
  #     ports:
  #       - "8888:8888"
  #     restart: always
