name: CI - Biomechanics Web App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend - Python checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: Backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Flask imports
        run: python -c "import flask; print('Flask successfully imported')"

  frontend:
    name: Frontend - Install only (no build)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: Frontend/upload
        run: npm install

      - name: Skip build (using static HTML)
        run: echo "Skipping build step - using static HTML in /pages"

